version: '2.1'
services:
  api-gateway:
    container_name: api-gateway
    build: .
    environment:
      PORT: '5000'
      SHOW_URLS: 'true'

      # Destinos
      DESTINATIONS_URL: '35.247.250.23'
      DESTINATIONS_PORT: '3000'
      DESTINATIONS_ENTRY: 'destinations'
      
      # Eventos
      EVENTS_URL: '35.247.250.23'
      EVENTS_PORT: '3003'
      EVENTS_ENTRY: 'events'
      RESERVATIONS_URL: '35.247.250.23'
      RESERVATIONS_PORT: '3003'
      RESERVATIONS_ENTRY: 'reservations'
      
      # Login
      USERS_URL: '35.247.250.23'
      USERS_PORT: '4000'
      USERS_ENTRY: 'users'
      PASSENGERS_URL: '35.247.250.23'
      PASSENGERS_PORT: '4000'
      PASSENGERS_ENTRY: 'passengers'
      CREWS_URL: '35.247.250.23'
      CREWS_PORT: '4000'
      CREWS_ENTRY: 'crews'

      # Notifications
      NOTIFICATIONS_URL: '35.247.250.23'
      NOTIFICATIONS_PORT: '3002'
      NOTIFICATIONS_ENTRY: 'notifications'
      
      # Promociones
      PROMOCIONES_URL: '35.247.250.23'
      PROMOCIONES_PORT: '3004'
      PROMOCIONES_ENTRY: 'promociones'
      TIENDAS_URL: '35.247.250.23'
      TIENDAS_PORT: '3004'
      TIENDAS_ENTRY: 'tiendas'

      # Servidor LDAP
      LDAP_URL:  '35.247.250.23'
      LDAP_PORT: '4000'
      LDAP_ENTRYA:  'auth'
      LDAP_ENTRYAa: 'authAdmin'
      LDAP_ENTRYAd: 'add'
      LDAP_ENTRYAda: 'addAdmin'
      LDAP_ENTRYV: 'validate'

    ports:
      - '5000:5000'
